name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        
      - name: List directory contents before build
        run: ls -la

      - name: Build
        run: bun run build -- --base /talks/2024-06-22/ 

      - name: List directory contents after build
        run: ls -la

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: talks/2024-06-22/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
